* Lathe-automatic complex
LAC == ТАК (токарно-автоматний комплекс)
** Directory structure
*** ENC-EP50S8
EP50S8 encoder reader.
**** Pin values
The encoder output has a weight based on 2, an exponent of N, and is a BCD code of 8-4-2-1.

| *Color*      | *Value Ex* | *Value Deg* | *Digital Pin* | *Pin Register* |
| Brown        | 2 ex 0     |           1 |            16 | PC2            |
| Red          | 2 ex 1     |           2 |            17 | PC3            |
| Orange       | 2 ex 2     |           4 |            18 | PC4            |
| Yellow       | 2 ex 3     |           8 |            19 | PC5            |
| Blue         | 2 ex 0*10  |          10 |            12 | PB4            |
| Violet       | 2 ex 1*10  |          20 |            14 | PC0            |
| Gray         | 2 ex 2*10  |          40 |            15 | PC1            |
| White/Brown  | 2 ex 3*10  |          80 |             8 | PB0            |
| White/Red    | 2 ex 0*100 |         100 |             9 | PB1            |
| White/Orange | 2 ex 1*100 |         200 |            10 | PB2            |
| White/Yellow | 2 ex 2*100 |         400 |            11 | PB3            |

**** Encoder reader communication
#+BEGIN_EXAMPLE
The encoder reader sends data via Modbus RTU protocol.
Slave configuration...: address = 3, start reference = 0, count = 1
Communication.........: 9600-8N1
Data type.............: 16-bit register, output (holding) register table
#+END_EXAMPLE
You can read the encoder this way:
#+BEGIN_SRC sh
mbpoll -0 -B -m rtu -a 3 -b 9600 -l 200 -t 4 -r 0 -c 1 -P none /dev/ttyUSB0
#+END_SRC

mbpoll is a Modbus reader app available in the Ubuntu repository or [[Github][https://github.com/epsilonrt/mbpoll]].

*** INPUT
Reads 32 digital board inputs. 28 inputs read via MCP23017 I/O expander and 4 via ATMega 368 pins (D7-D10).
GPA7 and GPB7 cannot be used as inputs because has possible problems.
Code controls MCP23017 using [[https://github.com/blemasle/arduino-mcp23017][arduino mcp23017 library]].

You can read inputs state using Modbus RTU protocol this way:
1. Check the DTR pin is disabled.
2. Check protocol configuration according to below:
#+BEGIN_EXAMPLE
Protocol configuration: Modbus RTU
Slave configuration...: address = [10]
                        start reference = 1, count = 32
Communication.........: /dev/ttyUSB0,       9600-8N1 
                        t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, output (holding) register table
#+END_EXAMPLE

Reading example:
#+BEGIN_EXAMPLE
$ mbpoll -B -m rtu -a 10 -b 9600 -t 4 -r 1 -c 32 -P none /dev/ttyUSB0
-- Polling slave 10... Ctrl-C to stop)
[1]:    1
[2]:    0
[3]:    0
[4]:    1
[5]:    1
...
[31]:   1
[32]:   1
#+END_EXAMPLE

*** TestBoard directory
LGT8F328P based Arduino Nano clone uses as test board
**** Install board and project
#+BEGIN_EXAMPLE
pio upgrade
pio pkg install -g -p "https://github.com/darkautism/pio-lgt8fx.git"
pio init -b LGT8F328P
#+END_EXAMPLE

**** Minimal platformio.ini
#+BEGIN_EXAMPLE
[env:LGT8F328P]
platform = lgt8f
board = LGT8F328P
framework = arduino
board_build.f_cpu=16000000L
;internal clock
board_build.clock_source=1
#+END_EXAMPLE

**** Extended platformio.ini params
#+BEGIN_EXAMPLE
[env:LGT8F328P]
...
monitor_speed = 9600
upload_speed = 57600
board_build.f_cpu = 32000000L
board_build.clock_source = 1
...
#+END_EXAMPLE

**** Links
1. https://registry.platformio.org/platforms/darkautism/lgt8f
2. https://community.platformio.org/t/lgt8f328p-with-platformio-and-vscode-unknown-platform/35072/23
3. http://www.ur5ffr.com/viewtopic.php?t=369
4. https://www.electronicshub.org/binary-codes/
5. https://uk.wikipedia.org/wiki/%D0%94%D0%B2%D1%96%D0%B9%D0%BA%D0%BE%D0%B2%D0%BE-%D0%B4%D0%B5%D1%81%D1%8F%D1%82%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9_%D0%BA%D0%BE%D0%B4
